### ISSUE TITLE
what are the significance of _WALLETINTERFACE address ?

### ISSUE THREAD

**Issue by jatin192** [jiko23/Multi-Sig-Wallet#1]
what is the significance of  _WALLETINTERFACE address that are using as an input in MultiSignatureWalletContract.sol   and from where and how can i get this address  ?

**Comment by jiko23** [comment]
Hi Jatin,
Are you asking regarding getting the interface address?
or
Are you asking how to get the address of owners that are in wallet?

**Comment by jiko23** [comment]
@jatin192 
When we want to interact with other smart contract without having their code that time we need interface.
